// MOVIE ACTIONS TYPES
export const MOVIE_LOADING_START = "MOVIE_LOADING_START";
export const MOVIE_LOADING_SUCCESS = "MOVIE_LOADING_SUCCESS";
export const MOVIE_LOADING_ERROR = "MOVIE_LOADING_ERROR";
export const MOVIE_DATA_SET = "MOVIE_DATA_SET";
export const MOVIE_DATA_GET = "MOVIE_DATA_GET";
export const MOVIE_DATA_CLEAR = "MOVIE_DATA_CLEAR";

// SEARCH ACTION TYPES
export const SET_SEARCH_FILTER = 'SET_SEARCH_BY';
export const SET_SEARCH_TEXT = 'SET_SEARCH_TEXT';
export const SET_SEARCH_RESULTS_CRITERIA = 'SET_SEARCH_RESULTS_CRITERIA';
