// LOAD MOVIE ACTIONS:
export const SET_LOADING_MOVIE_STATUS = 'MOVIE_LOADING_STATUS';
export const CLEAR_LOADING_STATUS = 'CLEAR_LOADING_STATUS';

export const MOVIE_LOADING_START = 'MOVIE_LOADING_START';
export const MOVIE_LOADING_END = 'MOVIE_LOADING_END';
export const MOVIE_LOADING_ERROR = 'MOVIE_LOADING_ERROR';
export const MOVIE_LOADING_SUCCESS = 'MOVIE_LOADING_SUCCESS';

// FORM SEARCH ACTIONS:
export const SET_SEARCH_FILTER = 'SET_SEARCH_BY';
export const SET_SEARCH_TEXT = 'SET_SEARCH_TEXT';
export const SET_SEARCH_SORT = 'SET_SEARCH_SORT';
export const CLICK_GENRE_TITLE = 'CLICK_GENRE_TITLE';

// SEARCH ACTIONS:
export const APPLY_SEARCH = 'APPLY_SEARCH';
export const DO_SEARCH = 'DO_SEARCH';

// DETAIL MOVIE ACTIONS:
export const DETAIL_MOVIE = 'DETAIL_MOVIE';
