// SEARCH BOX
export const CAPTION_SEARCH_TITLE = "FIND YOUR MOVIE";
export const CAPTION_SEARCH_FIELD = "Search ...";
export const CAPTION_ByTITLE_BUTTON = "TITLE";
export const CAPTION_ByGENRE_BUTTON = "GENRE";
export const CAPTION_SEARCH_TOOLBAR = "SEARCH BY";
export const CAPTION_SEARCH_BUTTON = "SEARCH";
